#!/bin/sh
# /boot/xinitrc
while true; do
  #
  # Clean up previously running apps, gracefully at first then harshly
  killall -TERM matchbox-window-manager 2>/dev/null;
  sleep 2;
  killall -9 matchbox-window-manager 2>/dev/null;
  #
  # Disable DPMS / Screen blanking
  xset -dpms
  xset s off
  xset s noblank
  #
  # Reset the framebuffer's colour-depth
  fbset -depth $( cat /sys/module/*fb*/parameters/fbdepth );
  #
  # Hide the cursor (move it to the bottom-right, comment out if you want mouse interaction)
  xwit -root -warp $( cat /sys/module/*fb*/parameters/fbwidth ) $( cat /sys/module/*fb*/parameters/fbheight )
  #
  # https://www.scalzotto.nl/posts/raspberry-pi-kiosk/
  # Hide the mouse cursor.
  unclutter -idle 1 -root &
  #
  # Start the window manager (remove "-use_cursor no" if you actually want mouse interaction)
  matchbox-window-manager -use_titlebar no -use_cursor no &
  #
  if [ ! -f /home/jdg/.skip.surf ]; then
    # Start the browser:
    # surf http://127.0.0.1/
    #surf http://127.0.0.1:1080/
    chromium-browser --kiosk --noerrdialogs --disable-infobars http://127.0.0.1:1080/web/#/display
  else
    sleep 5
  fi
	#
	# NOTE: the browser will auto-restart if killed/exit
	#
done;
#
